<?php

// This is a compiled Agavi configuration file
// Compiled from: /srv/http/market/app/config/compile.xml
// Generated by: AgaviCompileConfigHandler
// Date: 2012-09-26T07:35:02+0000

require('/srv/http/market/libs/agavi/util/AgaviAttributeHolder.class.php');
require('/srv/http/market/libs/agavi/action/AgaviAction.class.php');
require('/srv/http/market/libs/agavi/core/AgaviContext.class.php');
require('/srv/http/market/libs/agavi/controller/AgaviController.class.php');
require('/srv/http/market/libs/agavi/controller/AgaviExecutionContainer.class.php');
require('/srv/http/market/libs/agavi/controller/AgaviOutputType.class.php');
require('/srv/http/market/libs/agavi/filter/AgaviIFilter.interface.php');
require('/srv/http/market/libs/agavi/filter/AgaviIGlobalFilter.interface.php');
require('/srv/http/market/libs/agavi/filter/AgaviIActionFilter.interface.php');
require('/srv/http/market/libs/agavi/filter/AgaviFilter.class.php');
require('/srv/http/market/libs/agavi/filter/AgaviActionExecutionFilter.class.php');
require('/srv/http/market/libs/agavi/filter/AgaviDispatchFilter.class.php');
require('/srv/http/market/libs/agavi/filter/AgaviExecutionFilter.class.php');
require('/srv/http/market/libs/agavi/filter/AgaviFilterChain.class.php');
require('/srv/http/market/libs/agavi/renderer/AgaviRenderer.class.php');
require('/srv/http/market/libs/agavi/request/AgaviIParametersRequestDataHolder.interface.php');
require('/srv/http/market/libs/agavi/request/AgaviRequestDataHolder.class.php');
require('/srv/http/market/libs/agavi/request/AgaviRequest.class.php');
require('/srv/http/market/libs/agavi/response/AgaviResponse.class.php');
require('/srv/http/market/libs/agavi/routing/AgaviRouting.class.php');
require('/srv/http/market/libs/agavi/storage/AgaviStorage.class.php');
require('/srv/http/market/libs/agavi/user/AgaviUser.class.php');
require('/srv/http/market/libs/agavi/view/AgaviTemplateLayer.class.php');
require('/srv/http/market/libs/agavi/view/AgaviView.class.php');

?>