<?php

// This is a compiled Agavi configuration file
// Compiled from: /srv/http/market/app/modules/Welcome/config/module.xml
// Generated by: AgaviModuleConfigHandler
// Date: 2012-09-26T07:35:02+0000

$lcModuleName = strtolower($moduleName);
AgaviConfig::set(AgaviToolkit::expandVariables('modules.${moduleName}.enabled', array('moduleName' => $lcModuleName)), true, true, true);
$moduleConfig = array (
  'modules.${moduleName}.title' => 'Welcome Module',
  'modules.${moduleName}.version' => '1.0',
  'modules.${moduleName}.agavi.action.path' => '/srv/http/market/app/modules/${moduleName}/actions/${actionName}Action.class.php',
  'modules.${moduleName}.agavi.view.path' => '/srv/http/market/app/modules/${moduleName}/views/${viewName}View.class.php',
  'modules.${moduleName}.agavi.view.name' => '${actionName}${viewName}',
  'modules.${moduleName}.agavi.cache.path' => '/srv/http/market/app/modules/${moduleName}/cache/${actionName}.xml',
  'modules.${moduleName}.agavi.validate.path' => '/srv/http/market/app/modules/${moduleName}/validate/${actionName}.xml',
  'modules.${moduleName}.agavi.template.directory' => '/srv/http/market/app/modules/../templates/${module}',
);
$moduleConfigKeys = array_keys($moduleConfig);
foreach($moduleConfigKeys as &$value) $value = AgaviToolkit::expandVariables($value, array('moduleName' => $lcModuleName));
$moduleConfig = array_combine($moduleConfigKeys, $moduleConfig);
AgaviConfig::fromArray($moduleConfig);

?>