<?php

// This is a compiled Agavi configuration file
// Compiled from: /srv/http/market/app/config/settings.xml
// Generated by: AgaviSettingConfigHandler
// Date: 2012-09-26T07:35:02+0000

AgaviConfig::fromArray(array (
  'actions.default_module' => 'Appliance',
  'actions.default_action' => 'Index',
  'actions.error_404_module' => 'Welcome',
  'actions.error_404_action' => 'Error404',
  'actions.unavailable_module' => 'Welcome',
  'actions.unavailable_action' => 'Unavailable',
  'actions.module_disabled_module' => 'Welcome',
  'actions.module_disabled_action' => 'ModuleDisabled',
  'actions.secure_module' => 'Welcome',
  'actions.secure_action' => 'Secure',
  'actions.login_module' => 'Welcome',
  'actions.login_action' => 'Login',
  'core.app_name' => 'Market',
  'core.available' => true,
  'core.debug' => false,
  'core.use_database' => false,
  'core.use_logging' => false,
  'core.use_security' => true,
  'core.use_translation' => false,
  'exception.default_template' => '/srv/http/market/libs/agavi/exception/templates/shiny.php',
  'exception.templates.console' => '/srv/http/market/libs/agavi/exception/templates/plaintext.php',
));

?>